name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Login to Docker
      run: docker login -u="stevenjambonae+bent_melis" -p="N8DQ64QAN105HYJW039DMSJTDURJTFTPKW21REH5KF8397NDD8XFLZWI93Z986FK" quay.io
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag sjambon/alm-workshop:$(date +%s)
    - name: push container to Quay
      run: docker push sjambon/alm-workshop:$(date +%s) quay.io
    
